language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

deploy:
  provider: pypi
  user: dizak
  password: $pypi_passwd
  distributions: sdist
  on:
    tags: true
    branch: master
    python: 3.6

install:
  - python setup.py sdist
  - pip install dist/mothulity-*.tar.gz

before_script:
  - mkdir $HOME/db/
  - hash ktImportXML
  - hash mothur

script:
# Doctests
  - python -m doctest mothulity/utilities.py -v
# Unittests
  - python -m unittest -v tests.tests
# Database download test
  - mothulity_dbaser $HOME/db --unite-ITS-02
# Set persistent databases paths
  - mothulity --set-align-database-path test_data/database/t19.align --set-taxonomy-database-path test_data/database/t19.tax
# Run new analysis on multiple samples.
  - mothulity test_data/new_run/mltp_smpl/fastq -r bash -n travis_job
## Check results files list
  - ls --hide mothur*logfile test_data/new_run/mltp_smpl/fastq/  > test_files_list
  - diff test_data/new_run/mltp_smpl/results/files_list test_files_list --ignore-blank-lines --ignore-trailing-space --ignore-matching-lines "mothur*logfile"
## Check shared file content
  - diff <(awk '{print $1,$2}' test_data/new_run/mltp_smpl/fastq/*shared) <(awk '{print $1,$2}' test_data/analysis/mltp_smpl/shared_tax/*shared)
## Check tax.summary file content
  - diff <(awk '{if ($1 <= 3) print $1,$2,$3}' test_data/new_run/mltp_smpl/fastq/*cons.tax.summary) <(awk '{if ($1 <= 3) print $1,$2,$3}' test_data/analysis/mltp_smpl/shared_tax/*cons.tax.summary)
## Check the HTML report presence
  - ls test_data/new_run/mltp_smpl/fastq/analysis/OTU/analysis_travis_job.html
## Check the script content
  - diff test_data/new_run/mltp_smpl/script/travis_job.sh travis_job.sh --ignore-blank-lines --ignore-trailing-space
# Run new analysis on a single sample.
  - mothulity test_data/new_run/single_smpl/fastq -r bash -n travis_job
## Check results files list
  - ls --hide mothur*logfile test_data/new_run/single_smpl/fastq/  > test_files_list
  - diff test_data/new_run/single_smpl/results/files_list test_files_list --ignore-blank-lines --ignore-trailing-space --ignore-matching-lines "mothur*logfile"
## Check shared file content
  - diff <(awk '{print $1,$2}' test_data/new_run/single_smpl/fastq/*shared) <(awk '{print $1,$2}' test_data/analysis/single_smpl/shared_tax/*shared)
## Check tax.summary file content
  - diff <(awk '{if ($1 <= 3) print $1,$2,$3}' test_data/new_run/single_smpl/fastq/*cons.tax.summary) <(awk '{if ($1 <= 3) print $1,$2,$3}' test_data/analysis/single_smpl/shared_tax/*cons.tax.summary)
## Check the HTML report presence 
  - ls test_data/new_run/single_smpl/fastq/analysis/OTU/analysis_travis_job.html
## Check the script content
  - diff test_data/new_run/single_smpl/script/travis_job.sh travis_job.sh --ignore-blank-lines --ignore-trailing-space
# Run analysis on multiple samples
  - mothulity test_data/analysis/mltp_smpl/shared_tax -r bash -n analysis_travis_job --analysis-only
## Check results files list
  - ls --hide mothur*logfile test_data/analysis/mltp_smpl/shared_tax/analysis/OTU/ > test_files_list
  - diff test_data/analysis/mltp_smpl/results/files_list test_files_list --ignore-blank-lines --ignore-trailing-space --ignore-matching-lines "mothur*logfile"
## Check the script content
  - diff test_data/analysis/mltp_smpl/script/analysis_travis_job.sh analysis_travis_job.sh --ignore-blank-lines --ignore-trailing-space
# Run analysis on a single sample
  - mothulity test_data/analysis/single_smpl/shared_tax -r bash -n analysis_travis_job --analysis-only
## Check results files list
  - ls --hide mothur*logfile test_data/analysis/single_smpl/shared_tax/analysis/OTU/ > test_files_list
  - diff test_data/analysis/single_smpl/results/files_list test_files_list --ignore-blank-lines --ignore-trailing-space --ignore-matching-lines "mothur*logfile"
## Check the script content
  - diff test_data/analysis/single_smpl/script/analysis_travis_job.sh analysis_travis_job.sh --ignore-blank-lines --ignore-trailing-space
# Remove run
  - rm -r test_data/new_run/mltp_smpl/fastq/!(*fastq)
# Check slurm add/list/use
## Add slurm setting
  - mothulity . --add-slurm-setting "name=travis partition=test nodes=1 processors=12 exclusive"
## List slurm setting
  - diff <(mothulity . --list-slurm-settings | sort) <(sort test_data/logs/list_slurm_settings.log) --ignore-blank-lines --ignore-trailing-space
## Generate mothur script with slurm flags
  - mothulity test_data/new_run/mltp_smpl/fastq --dry-run -r sbatch -n travis_job_slurm --use-slurm-setting travis
  - cat travis_job_slurm.sh
  - diff <(sort test_data/new_run/mltp_smpl/script/travis_job_slurm.sh) <(sort travis_job_slurm.sh) --ignore-blank-lines --ignore-trailing-space
# Check how mothulity refuses to work with dashed directories
  - mothulity test_data/dashed-dir/fastq --dry-run -r bash > test_dashed_path.log
  - diff test_data/logs/dashed_path.log test_dashed_path.log --ignore-blank-lines --ignore-trailing-space
# Check how mothulty saves setting to config file before running the analysis
  - mothulity test_data/new_run/mltp_smpl/fastq --dry-run -r bash -n travis_job --set-main-config-path test_data/config/mothulity.config > test_config_success.log
  - diff test_data/logs/config_success.log test_config_success.log --ignore-blank-lines --ignore-trailing-space
# Check how mothulity refuses to save settign to non-existing config file
  - mothulity test_data/new_run/mltp_smpl/fastq --dry-run -r bash -n travis_job --set-main-config-path test_data/config/ > test_config_fail.log
  - diff test_data/logs/config_fail.log test_config_fail.log --ignore-blank-lines --ignore-trailing-space

notifications:
  email:
    on_success: never
    on_failure: always
