language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

deploy:
  provider: pypi
  user: dizak
  password: $pypi_passwd
  distributions: sdist
  on:
    tags: true
    branch: master
    python: 3.6

install:
  - python setup.py sdist
  - pip install dist/mothulity-*.tar.gz

before_script:
  - mkdir $HOME/db/
  - hash ktImportXML
  - hash mothur

script:
# Doctests
  - python -m doctest mothulity/utilities.py -v
# Unittests
  - python -m unittest -v tests.tests
# Database download test
  - mothulity_dbaser $HOME/db --unite-ITS-02
# Set persistent databases paths
  - mothulity --set-align-database-path test_data/database/t19.align --set-taxonomy-database-path test_data/database/t19.tax
# Run new analysis on multiple samples
  - mothulity test_data/new_run/mltp_smpl/fastq -r bash -n travis_job
## Check results files list
  - ls !(mothur*logfile) -d > test_files_list
  - diff test_data/new_run/mltp_smpl/results/files_list test_files_list --ignore-blank-lines --ignore-trailing-space
## Check the script content
  - diff test_data/new_run/mltp_smpl/script/travis_job.sh travis_job.sh --ignore-blank-lines --ignore-trailing-space
# Run new analysis on a single sample
  - mothulity test_data/new_run/single_smpl/fastq -r bash -n travis_job
## Check results files list
  - ls !(mothur*logfile) -d > test_files_list
  - diff test_data/new_run/single_smpl/results/files_list test_files_list --ignore-blank-lines --ignore-trailing-space
## Check the script content
  - diff test_data/new_run/single_smpl/script/travis_job.sh travis_job.sh --ignore-blank-lines --ignore-trailing-space
# Run analysis on multiple samples
  - diff test_data/analysis/mltp_smpl/script/analysis_travis_job.sh analysis_travis_job.sh --ignore-blank-lines --ignore-trailing-space
  - mothulity test_data/analysis/single_smpl/shared_tax --dry-run -r bash -n analysis_travis_job --analysis-only
  - diff test_data/analysis/single_smpl/script/analysis_travis_job.sh analysis_travis_job.sh --ignore-blank-lines --ignore-trailing-space
  - mothulity test_data/dashed-dir/fastq --dry-run -r bash > test_dashed_path.log
  - diff test_data/logs/dashed_path.log test_dashed_path.log --ignore-blank-lines --ignore-trailing-space
  - mothulity test_data/new_run/mltp_smpl/fastq --dry-run -r bash -n travis_job --set-main-config-path test_data/config/mothulity.config > test_config_success.log
  - diff test_data/logs/config_success.log test_config_success.log --ignore-blank-lines --ignore-trailing-space
  - mothulity test_data/new_run/mltp_smpl/fastq --dry-run -r bash -n travis_job --set-main-config-path test_data/config/ > test_config_fail.log
  - diff test_data/logs/config_fail.log test_config_fail.log --ignore-blank-lines --ignore-trailing-space

notifications:
  email:
    on_success: never
    on_failure: always
