language: python

os: linux

env:
  - CONDA_PY=2
  - CONDA_PY=3

install:
  - wget https://repo.continuum.io/miniconda/Miniconda${CONDA_PY}-latest-Linux-x86_64.sh
  - bash Miniconda${CONDA_PY}-latest-Linux-x86_64.sh -b -p $HOME/miniconda${CONDA_PY}
  - export PATH=$HOME/miniconda${CONDA_PY}/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a

before_script:
  - mkdir $HOME/db/

script:
  - echo "  - python=${CONDA_PY}" >> mothulity.yaml
  - ./INSTALL.sh -p $HOME/db/ -t 1 -y
  - source $HOME/.bashrc
  - source activate mothulity
  - python -m doctest *py -v
  - python -m unittest -v tests.tests
  - mothulity.py test_data/new_run/mltp_smpl/fastq --dry-run -r bash -n travis_job
  - diff test_data/new_run/mltp_smpl/script/travis_job.sh travis_job.sh --ignore-blank-lines --ignore-trailing-space
  - mothulity.py test_data/analysis/mltp_smpl/shared_tax --dry-run -r bash -n analysis_travis_job --analysis-only
  - diff test_data/analysis/mltp_smpl/script/analysis_travis_job.sh analysis_travis_job.sh --ignore-blank-lines --ignore-trailing-space
  - mothulity.py test_data/new_run/single_smpl/fastq --dry-run -r bash -n travis_job
  - diff test_data/new_run/single_smpl/script/travis_job.sh travis_job.sh --ignore-blank-lines --ignore-trailing-space
  - mothulity.py test_data/analysis/single_smpl/shared_tax --dry-run -r bash -n analysis_travis_job --analysis-only
  - diff test_data/analysis/single_smpl/script/analysis_travis_job.sh analysis_travis_job.sh --ignore-blank-lines --ignore-trailing-space
  - mothulity.py test_data/dashed-dir/fastq --dry-run -r bash > test_dashed_path.log
  - diff test_data/logs/dashed_path.log test_dashed_path.log --ignore-blank-lines --ignore-trailing-space
  - mothulity.py test_data/new_run/mltp_smpl/fastq --dry-run -r bash -n travis_job --set-config-path test_data/config/mothulity.config > test_config_success.log
  - diff test_data/logs/config_success.log test_config_success.log --ignore-blank-lines --ignore-trailing-space
  - mothulity.py test_data/new_run/mltp_smpl/fastq --dry-run -r bash -n travis_job --set-config-path test_data/config/ > test_config_fail.log
  - diff test_data/logs/config_fail.log test_config_fail.log --ignore-blank-lines --ignore-trailing-space

notifications:
  email:
    on_success: never
    on_failure: always
